# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.cache/wt [current_project]
set_property parent.project_path C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Joel7/Desktop/125/Lab9final/Lab9final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/ALU.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/CLA_generator.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/new/CU.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/CUALU.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/new/CU_FULL.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/lab8/DP.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/DPALU.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/new/DP_FULL.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/Dregister.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/HA.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/HA_topmodule.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/LED7segment.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/MUX1ALU.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/MUX2ALU.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/new/MUX4.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/RFALU.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/new/TOPFULL.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/new/TOP_DIVIDER.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/X_OR.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/clk_gen.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/debounce2.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/eightbitsadder.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/fpga.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/led_mux.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/lab8/lt_comparator.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/multiplier_top.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/lab8/mux2.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/ppcalculator.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/shifter1.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/shifter2.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/shifter3.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/lab8/shifter_register.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/lab8/substractor.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/new/topALU.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/imports/lab8/ud_counter.v
  C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/sources_1/new/TOPFULLFPGA.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/constrs_1/new/FULL.xdc
set_property used_in_implementation false [get_files C:/Users/Joel7/Desktop/125/Lab9final/Lab9final.srcs/constrs_1/new/FULL.xdc]


synth_design -top TOPFULLFPGA -part xc7a100tcsg324-1


write_checkpoint -force -noxdef TOPFULLFPGA.dcp

catch { report_utilization -file TOPFULLFPGA_utilization_synth.rpt -pb TOPFULLFPGA_utilization_synth.pb }
